#ifndef ROUTE_CHOSE_H
#define ROUTE_CHOSE_H

/*void A_route(unsigned char color);
void B_route(unsigned char color);
void C_route(unsigned char color);

void A_A_route();
void A_B_route();
void A_C_route();
void A_D_route();
void A_E_route();

void B_A_route();
void B_B_route();
void B_C_route();
void B_D_route();
void B_E_route();

void C_A_route();
void C_B_route();
void C_C_route();
void C_D_route();
void C_E_route();*/

void L_R_MID();

#endif